name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.0"]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@2654679fe7f7c29875c669398a8ec0791b8a64a1 # v1.215.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Build gem
      run: bundle exec rake

    - name: Run RuboCop
      run: bundle exec rake rubocop

    - name: Run tests
      run: bundle exec rake spec
