name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1', '3.0', '2.7', '2.6']

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Build gem
      run: bundle exec rake

    - name: Run RuboCop
      run: bundle exec rake rubocop

    - name: Run tests
      run: bundle exec rake spec
