name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.0"]

    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      with:
        persist-credentials: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@52753b7da854d5c07df37391a986c76ab4615999 # v1.191.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Build gem
      run: bundle exec rake

    - name: Run RuboCop
      run: bundle exec rake rubocop

    - name: Run tests
      run: bundle exec rake spec
