name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.1", "3.0"]

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Build gem
      run: bundle exec rake

    - name: Run RuboCop
      run: bundle exec rake rubocop

    - name: Run tests
      run: bundle exec rake spec
